%% Creeam un "Datastore" cu imaginile de antrenare
% Acest cod se va antrena cu imagini alb-negru 
% care contin informatia de pe canalul G
% CNN supervizat


categories = {'Hem','NonHem'};%Folderele unde se gasesc cele 20000 de imagini
categoriesV = {'Hem','NonHem'};
image_size = [55 55 3];
pixelRange = [-10 10];
rootFoldertrain = 'F:\Facultate\Licenta\BIG_DATA_Color';
rootFoldertrainV = 'F:\Facultate\Licenta\BIG_DATA_Color\Validation';
imds = imageDatastore(fullfile(rootFoldertrain, categories), ...
    'LabelSource', 'foldernames');
imdsV= imageDatastore(fullfile(rootFoldertrainV, categoriesV), ...
    'LabelSource', 'foldernames');


imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);
imdsAUG = augmentedImageSource(image_size,imds, ...
    'DataAugmentation',imageAugmenter);

%% Layers

layers = [...
    imageInputLayer(image_size)% Aici introducem dimensiunile matricei (imaginii)
    convolution2dLayer(5,20)
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2,'Stride',2) % Layer-uri basic care ar trebuii sa contina
    fullyConnectedLayer(2)          % orice CNN
    softmaxLayer
    classificationLayer];



%% OPTIONS Fixed
% 
% opts = trainingOptions('sgdm', ...
%     'MaxEpochs',100, ...
%     'Shuffle','every-epoch', ...
%     'Plots','training-progress', ...
%     'Verbose',true, ...
%     'ValidationData',imdsV,...
%     'ValidationPatience',Inf);

%% Options Dynamic
opts = trainingOptions('sgdm', ...
    'MaxEpochs',50, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'Verbose',true, ...
    'ValidationData',imdsV,...
    'ValidationPatience',Inf);
%% Train

[net, info] = trainNetwork(imdsAUG, layers, opts);

